import type { Metadata } from "next";
import localFont from "next/font/local";
import { NavMenu } from "./components/nav-menu";
import { Container } from "react-bootstrap";

import "./globals.scss";
import { Providers } from "./providers";
import { ToastContainer } from "@app/ui-components";
import { getDictionary, getCurrentLanguage } from "./dictionaries";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "TaskSync",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentLanguage = await getCurrentLanguage();
  const dictionary = await getDictionary(currentLanguage);

  return (
    <html lang={currentLanguage}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers dictionary={dictionary} currentLng={currentLanguage}>
          <ToastContainer />
          <NavMenu />
          <Container fluid="xl" style={{ paddingTop: 8 }}>
            {children}
          </Container>
        </Providers>
      </body>
    </html>
  );
}
