import type { Metadata } from "next";
import localFont from "next/font/local";
import { NavMenu } from "./components/nav-menu";
import { Container } from "react-bootstrap";

import "./globals.scss";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "TaskSync",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NavMenu />
        <Container fluid="xl" style={{ paddingTop: 8 }}>
          {children}
        </Container>
      </body>
    </html>
  );
}
